/*
 * Copyright (c) 2011-2015, Dan McNulty
 * All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

package net.sourcecrumbs.refimpl.dwarf.constants;

import org.codehaus.preon.annotation.BoundEnumOption;

/**
 * @author mcnulty
 */
public enum ExpressionOpCode
{
    @BoundEnumOption(0x03)
    DW_OP_addr(1),
    @BoundEnumOption(0x06)
    DW_OP_deref(0),
    @BoundEnumOption(0x08)
    DW_OP_const1u(1),
    @BoundEnumOption(0x09)
    DW_OP_const1s(1),
    @BoundEnumOption(0x0a)
    DW_OP_const2u(1),
    @BoundEnumOption(0x0b)
    DW_OP_const2s(1),
    @BoundEnumOption(0x0c)
    DW_OP_const4u(1),
    @BoundEnumOption(0x0d)
    DW_OP_const4s(1),
    @BoundEnumOption(0x0e)
    DW_OP_const8u(1),
    @BoundEnumOption(0x0f)
    DW_OP_const8s(1),
    @BoundEnumOption(0x10)
    DW_OP_constu(1),
    @BoundEnumOption(0x11)
    DW_OP_consts(1),
    @BoundEnumOption(0x12)
    DW_OP_dup(0),
    @BoundEnumOption(0x13)
    DW_OP_drop(0),
    @BoundEnumOption(0x14)
    DW_OP_over(0),
    @BoundEnumOption(0x15)
    DW_OP_pick(1),
    @BoundEnumOption(0x16)
    DW_OP_swap(0),
    @BoundEnumOption(0x17)
    DW_OP_rot(0),
    @BoundEnumOption(0x18)
    DW_OP_xderef(0),
    @BoundEnumOption(0x19)
    DW_OP_abs(0),
    @BoundEnumOption(0x1a)
    DW_OP_and(0),
    @BoundEnumOption(0x1b)
    DW_OP_div(0),
    @BoundEnumOption(0x1c)
    DW_OP_minus(0),
    @BoundEnumOption(0x1d)
    DW_OP_mod(0),
    @BoundEnumOption(0x1e)
    DW_OP_mul(0),
    @BoundEnumOption(0x1f)
    DW_OP_neg(0),
    @BoundEnumOption(0x20)
    DW_OP_not(0),
    @BoundEnumOption(0x21)
    DW_OP_or(0),
    @BoundEnumOption(0x22)
    DW_OP_plus(0),
    @BoundEnumOption(0x23)
    DW_OP_plus_uconst(1),
    @BoundEnumOption(0x24)
    DW_OP_shl(0),
    @BoundEnumOption(0x25)
    DW_OP_shr(0),
    @BoundEnumOption(0x26)
    DW_OP_shra(0),
    @BoundEnumOption(0x27)
    DW_OP_xor(0),
    @BoundEnumOption(0x2f)
    DW_OP_skip(1),
    @BoundEnumOption(0x28)
    DW_OP_bra(1),
    @BoundEnumOption(0x29)
    DW_OP_eq(0),
    @BoundEnumOption(0x2a)
    DW_OP_ge(0),
    @BoundEnumOption(0x2b)
    DW_OP_gt(0),
    @BoundEnumOption(0x2c)
    DW_OP_le(0),
    @BoundEnumOption(0x2d)
    DW_OP_lt(0),
    @BoundEnumOption(0x2e)
    DW_OP_ne(0),
    @BoundEnumOption(0x30)
    DW_OP_lit0(0),
    @BoundEnumOption(0x31)
    DW_OP_lit1(0),
    @BoundEnumOption(0x32)
    DW_OP_lit2(0),
    @BoundEnumOption(0x33)
    DW_OP_lit3(0),
    @BoundEnumOption(0x34)
    DW_OP_lit4(0),
    @BoundEnumOption(0x35)
    DW_OP_lit5(0),
    @BoundEnumOption(0x36)
    DW_OP_lit6(0),
    @BoundEnumOption(0x37)
    DW_OP_lit7(0),
    @BoundEnumOption(0x38)
    DW_OP_lit8(0),
    @BoundEnumOption(0x39)
    DW_OP_lit9(0),
    @BoundEnumOption(0x3a)
    DW_OP_lit10(0),
    @BoundEnumOption(0x3b)
    DW_OP_lit11(0),
    @BoundEnumOption(0x3c)
    DW_OP_lit12(0),
    @BoundEnumOption(0x3d)
    DW_OP_lit13(0),
    @BoundEnumOption(0x3e)
    DW_OP_lit14(0),
    @BoundEnumOption(0x3f)
    DW_OP_lit15(0),
    @BoundEnumOption(0x40)
    DW_OP_lit16(0),
    @BoundEnumOption(0x41)
    DW_OP_lit17(0),
    @BoundEnumOption(0x42)
    DW_OP_lit18(0),
    @BoundEnumOption(0x43)
    DW_OP_lit19(0),
    @BoundEnumOption(0x44)
    DW_OP_lit20(0),
    @BoundEnumOption(0x45)
    DW_OP_lit21(0),
    @BoundEnumOption(0x46)
    DW_OP_lit22(0),
    @BoundEnumOption(0x47)
    DW_OP_lit23(0),
    @BoundEnumOption(0x48)
    DW_OP_lit24(0),
    @BoundEnumOption(0x49)
    DW_OP_lit25(0),
    @BoundEnumOption(0x4a)
    DW_OP_lit26(0),
    @BoundEnumOption(0x4b)
    DW_OP_lit27(0),
    @BoundEnumOption(0x4c)
    DW_OP_lit28(0),
    @BoundEnumOption(0x4d)
    DW_OP_lit29(0),
    @BoundEnumOption(0x4e)
    DW_OP_lit30(0),
    @BoundEnumOption(0x4f)
    DW_OP_lit31(0),
    @BoundEnumOption(0x50)
    DW_OP_reg0(0),
    @BoundEnumOption(0x51)
    DW_OP_reg1(0),
    @BoundEnumOption(0x52)
    DW_OP_reg2(0),
    @BoundEnumOption(0x53)
    DW_OP_reg3(0),
    @BoundEnumOption(0x54)
    DW_OP_reg4(0),
    @BoundEnumOption(0x55)
    DW_OP_reg5(0),
    @BoundEnumOption(0x56)
    DW_OP_reg6(0),
    @BoundEnumOption(0x57)
    DW_OP_reg7(0),
    @BoundEnumOption(0x58)
    DW_OP_reg8(0),
    @BoundEnumOption(0x59)
    DW_OP_reg9(0),
    @BoundEnumOption(0x5a)
    DW_OP_reg10(0),
    @BoundEnumOption(0x5b)
    DW_OP_reg11(0),
    @BoundEnumOption(0x5c)
    DW_OP_reg12(0),
    @BoundEnumOption(0x5d)
    DW_OP_reg13(0),
    @BoundEnumOption(0x5e)
    DW_OP_reg14(0),
    @BoundEnumOption(0x5f)
    DW_OP_reg15(0),
    @BoundEnumOption(0x60)
    DW_OP_reg16(0),
    @BoundEnumOption(0x61)
    DW_OP_reg17(0),
    @BoundEnumOption(0x62)
    DW_OP_reg18(0),
    @BoundEnumOption(0x63)
    DW_OP_reg19(0),
    @BoundEnumOption(0x64)
    DW_OP_reg20(0),
    @BoundEnumOption(0x65)
    DW_OP_reg21(0),
    @BoundEnumOption(0x66)
    DW_OP_reg22(0),
    @BoundEnumOption(0x67)
    DW_OP_reg23(0),
    @BoundEnumOption(0x68)
    DW_OP_reg24(0),
    @BoundEnumOption(0x69)
    DW_OP_reg25(0),
    @BoundEnumOption(0x6a)
    DW_OP_reg26(0),
    @BoundEnumOption(0x6b)
    DW_OP_reg27(0),
    @BoundEnumOption(0x6c)
    DW_OP_reg28(0),
    @BoundEnumOption(0x6d)
    DW_OP_reg29(0),
    @BoundEnumOption(0x6e)
    DW_OP_reg30(0),
    @BoundEnumOption(0x6f)
    DW_OP_reg31(0),
    @BoundEnumOption(0x70)
    DW_OP_breg0(1),
    @BoundEnumOption(0x71)
    DW_OP_breg1(1),
    @BoundEnumOption(0x72)
    DW_OP_breg2(1),
    @BoundEnumOption(0x73)
    DW_OP_breg3(1),
    @BoundEnumOption(0x74)
    DW_OP_breg4(1),
    @BoundEnumOption(0x75)
    DW_OP_breg5(1),
    @BoundEnumOption(0x76)
    DW_OP_breg6(1),
    @BoundEnumOption(0x77)
    DW_OP_breg7(1),
    @BoundEnumOption(0x78)
    DW_OP_breg8(1),
    @BoundEnumOption(0x79)
    DW_OP_breg9(1),
    @BoundEnumOption(0x7a)
    DW_OP_breg10(1),
    @BoundEnumOption(0x7b)
    DW_OP_breg11(1),
    @BoundEnumOption(0x7c)
    DW_OP_breg12(1),
    @BoundEnumOption(0x7d)
    DW_OP_breg13(1),
    @BoundEnumOption(0x7e)
    DW_OP_breg14(1),
    @BoundEnumOption(0x7f)
    DW_OP_breg15(1),
    @BoundEnumOption(0x80)
    DW_OP_breg16(1),
    @BoundEnumOption(0x81)
    DW_OP_breg17(1),
    @BoundEnumOption(0x82)
    DW_OP_breg18(1),
    @BoundEnumOption(0x83)
    DW_OP_breg19(1),
    @BoundEnumOption(0x84)
    DW_OP_breg20(1),
    @BoundEnumOption(0x85)
    DW_OP_breg21(1),
    @BoundEnumOption(0x86)
    DW_OP_breg22(1),
    @BoundEnumOption(0x87)
    DW_OP_breg23(1),
    @BoundEnumOption(0x88)
    DW_OP_breg24(1),
    @BoundEnumOption(0x89)
    DW_OP_breg25(1),
    @BoundEnumOption(0x8a)
    DW_OP_breg26(1),
    @BoundEnumOption(0x8b)
    DW_OP_breg27(1),
    @BoundEnumOption(0x8c)
    DW_OP_breg28(1),
    @BoundEnumOption(0x8d)
    DW_OP_breg29(1),
    @BoundEnumOption(0x8e)
    DW_OP_breg30(1),
    @BoundEnumOption(0x8f)
    DW_OP_breg31(1),
    @BoundEnumOption(0x90)
    DW_OP_regx(1),
    @BoundEnumOption(0x91)
    DW_OP_fbreg(1),
    @BoundEnumOption(0x92)
    DW_OP_bregx(2),
    @BoundEnumOption(0x93)
    DW_OP_piece(1),
    @BoundEnumOption(0x94)
    DW_OP_deref_size(1),
    @BoundEnumOption(0x95)
    DW_OP_xderef_size(1),
    @BoundEnumOption(0x96)
    DW_OP_nop(0),
    @BoundEnumOption(0x97)
    DW_OP_push_object_address(0),
    @BoundEnumOption(0x98)
    DW_OP_call2(1),
    @BoundEnumOption(0x99)
    DW_OP_call4(1),
    @BoundEnumOption(0x9a)
    DW_OP_call_ref(1),
    @BoundEnumOption(0x9b)
    DW_OP_form_tls_address(0),
    @BoundEnumOption(0x9c)
    DW_OP_call_frame_cfa(0),
    @BoundEnumOption(0x9d)
    DW_OP_bit_piece(2),
    @BoundEnumOption(0x9e)
    DW_OP_implicit_value(2),
    @BoundEnumOption(0x9f)
    DW_OP_stack_value(0),
    @BoundEnumOption(0xe0)
    DW_OP_lo_user(0),
    @BoundEnumOption(0xff)
    DW_OP_hi_user(0),

    UNKOWN(0);

    private final int numOperands;

    private ExpressionOpCode(int numOperands)
    {
        this.numOperands = numOperands;
    }

}
